# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # Get the latest version from: https://github.com/pre-commit/pre-commit-hooks/releases
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.1 # Get the latest version from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_validate
      - id: terraform_tfsec
      - id: terraform_checkov
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.14.3
    hooks:
      - id: ggshield
        language: python
        stages: [commit]
        args: [ 'secret', 'scan', 'pre-commit' ]
