name: "honest-public-semantic-pull-request-workflow"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

permissions: read-all

jobs:
  semantic-pull-request:
    name: semantic-pull-request
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        name: Semantic Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
