concurrency: terraform-pagerduty-alerting-terratest

name: terratest
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

env:
  PAGERDUTY_TOKEN: ${{ secrets.PAGERDUTY_TOKEN }}
  TF_VAR_pagerduty_token: ${{ secrets.PAGERDUTY_TOKEN }}
jobs:
  terratest:
    name: terratest
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Go (1.23)
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
        id: go
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.0"
      - name: Run terratest
        run: |
          cd test
          go test -v -timeout 5m
      - name: Release
        if: github.event_name == 'push'
        uses: cycjimmy/semantic-release-action@v3
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          extra_plugins: |
            @semantic-release/git@10.0.1
            @semantic-release/exec@6.0.3
            @semantic-release/changelog@6.0.1
